### ISSUE TITLE
Can't get scavenger working

### ISSUE THREAD

**Issue by iDiegoNL** [Emzi0767/Discord-Emoji-Scavenger#1]
I can't get scavenger working for some reason. I followed all steps, and have the requirements installed.
This is the log:

```
Beginning quick scavenge
Beginning run
Locating Discord token
Token located at 'C:\Users\idieg\AppData\Roaming\discord\Local Storage\https_discordapp.com_0.localstorage'
Extracting token

Unhandled Exception: System.IO.IOException: The file 'C:\Users\idieg\AppData\Roaming\discord\Local Storage\https_discordapp.com_0.localstorage.tmp' already exists.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at EmoteScavenger.Program.ExtractToken(FileInfo dbf) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 63
   at EmoteScavenger.Program.Main(String[] args) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 30
```

**Comment by Emzi0767** [comment]
You ran it twice. Delete the file it points to and try again.
