### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by arceuss** [Emzi0767/Discord-Emoji-Scavenger#3]
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EmoteScavenger.Program.ExtractToken(FileInfo dbf) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 77
   at EmoteScavenger.Program.Main(String[] args) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 30

**Comment by Hinkiii** [comment]
Having the exact same error.

**Comment by Emzi0767** [comment]
Means your token is empty.

**Comment by Hinkiii** [comment]
How could it be empty, and what can you do to circumvent it?

**Comment by Emzi0767** [comment]
No idea to be honest - I haven't had the need to use this tool in a long time, nor do I have time to maintain it. I also provide no guarantees as to whether it will work at all or not. As per license notice: 

> software (...) is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
